# Generated by Django 4.2.5 on 2023-09-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='imgUrl',
            field=models.URLField(default='https://dummyimage.com/450x300/dee2e6/6c757d.jpg'),
        ),
    ]
